server:
  port: 0

spring:
  application:
    name: queue-for-reserve
  data:
    redis:
      host: 127.0.0.1
      port: 6379

scheduler:
  enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 63790

scheduler:
  enabled: false